export type TriggerChip = { label: string };

export const overviewData = {
  hero: {
    title: "Customer Risk & Recovery Copilot",
    subtitle:
      "AI decision support for customer payment risk, recovery actions, and policy-aware approvals.",
  },
  kpis: [
    { label: "Outstanding", value: "2.18M", note: "Total open balance" },
    { label: "Overdue", value: "1.03M", note: "Past due exposure" },
    { label: "High Risk", value: "6", note: "High or critical accounts" },
    { label: "Approvals", value: "2", note: "Pending manager actions" },
    { label: "Active AI", value: "1", note: "Live review currently running" },
    { label: "Review Time", value: "18s", note: "Average live review runtime" },
  ],
  criticalCases: [
    {
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      riskBand: "Critical",
      triageScore: 88,
      overdueExposure: "286,000",
      reason: "Exposure threshold crossed with invoices beyond 60 days.",
      chips: ["60+ days overdue", "Policy threshold", "Large exposure"],
      recommendation: "Pause new credit orders pending manager decision.",
    },
    {
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      riskBand: "Critical",
      triageScore: 84,
      overdueExposure: "241,500",
      reason: "Strategic account with worsening payment trend.",
      chips: ["Strategic account", "Order decline", "Overdue trend"],
      recommendation: "Escalate for finance manager exception review.",
    },
    {
      caseId: "case_012",
      customerName: "Horizon Foodservice Trading Sdn Bhd",
      riskBand: "Watchlist",
      triageScore: 63,
      overdueExposure: "39,200",
      reason: "Borderline account ideal for scenario simulation.",
      chips: ["Rising overdue trend", "Partial payments", "Order decline"],
      recommendation: "Schedule monitored recovery call.",
    },
  ],
  activeRuns: [
    {
      runId: "run_20260326_live_001",
      customerName: "GreenWave Hospitality Group",
      status: "Running",
      node: "Policy Check Agent",
      elapsed: "11s",
    },
  ],
  pendingApprovals: [
    {
      approvalId: "app_201",
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      action: "Pause new credit orders",
      priority: "High",
      waiting: "68 min",
    },
    {
      approvalId: "app_202",
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      action: "Temporary monitored exception",
      priority: "High",
      waiting: "31 min",
    },
  ],
};

export const portfolioRows = [
  {
    caseId: "case_013",
    customerName: "HarborCare Corporate Services Pte Ltd",
    segment: "Office & Corporate Facilities",
    region: "Singapore",
    triageScore: 14,
    riskBand: "Low",
    overdueBalance: "0",
    oldestOverdueDays: "0",
    triggers: ["Stable payments"],
    recommendation: "No action needed",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_012",
    customerName: "Horizon Foodservice Trading Sdn Bhd",
    segment: "Hospitality & F&B",
    region: "Malaysia",
    triageScore: 63,
    riskBand: "Watchlist",
    overdueBalance: "39,200",
    oldestOverdueDays: "31",
    triggers: ["Rising overdue trend", "Partial payments"],
    recommendation: "Schedule monitored recovery call",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_002",
    customerName: "Meridian Retail Mart Sdn Bhd",
    segment: "Retail Chains",
    region: "Malaysia",
    triageScore: 72,
    riskBand: "High",
    overdueBalance: "118,000",
    oldestOverdueDays: "53",
    triggers: ["Broken promises", "Late-payment streak"],
    recommendation: "Escalate collections and reduce exposure",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_011",
    customerName: "Titan Facility Management Pte Ltd",
    segment: "Facilities Management",
    region: "Singapore",
    triageScore: 88,
    riskBand: "Critical",
    overdueBalance: "162,000",
    oldestOverdueDays: "68",
    triggers: ["60+ days overdue", "Policy threshold"],
    recommendation: "Pause new credit orders pending approval",
    reviewMode: "Baseline",
  },
];

export const caseDetails: Record<string, any> = {
  case_012: {
    customerName: "Horizon Foodservice Trading Sdn Bhd",
    meta: "Hospitality & F&B | Malaysia | 2 years | Net 30 | Credit Limit 110,000 | Owner: Farah N.",
    badges: ["Strategic: No", "Tier: Core"],
    riskSnapshot: [
      { label: "Risk", value: "Watchlist" },
      { label: "Risk Score", value: "64" },
      { label: "Triage Score", value: "63" },
      { label: "Overdue", value: "39,200" },
      { label: "Oldest Due", value: "31d" },
      { label: "Approval", value: "Not required" },
    ],
    recommendation: {
      action: "Schedule monitored recovery call",
      why: "The account is near a threshold where another missed payment could trigger stronger controls.",
      tradeoff: "Balances risk control with relationship preservation while the customer is still engaged.",
      nextSteps: [
        "Call customer within 48 hours",
        "Confirm repayment timeline",
        "Rerun review if no payment arrives",
      ],
    },
    triage: {
      score: 63,
      riskBand: "Watchlist",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["Rising overdue trend", "Partial payments", "Order decline"],
    },
    riskDrivers: [
      "Rising overdue trend",
      "Partial payment stress",
      "Slight order decline",
      "Near policy threshold",
    ],
    notes: [
      "Customer committed to partial payment this week pending receivables collection.",
      "Account manager notes relationship remains recoverable with structured follow-up.",
      "Recent order values softened over the last 2 months.",
    ],
    policy: ["Borderline exposure review trigger active", "No hard approval threshold crossed yet"],
  },
};
