export type TriggerChip = { label: string };

export const overviewData = {
  hero: {
    title: "Customer Risk & Recovery Copilot",
    subtitle:
      "AI decision support for customer payment risk, recovery actions, and policy-aware approvals.",
  },
  kpis: [
    { label: "Outstanding", value: "2.18M", note: "Total open balance" },
    { label: "Overdue", value: "1.03M", note: "Past due exposure" },
    { label: "High Risk", value: "6", note: "High or critical accounts" },
    { label: "Approvals", value: "2", note: "Pending manager actions" },
    { label: "Active AI", value: "1", note: "Live review currently running" },
    { label: "Review Time", value: "18s", note: "Average live review runtime" },
  ],
  criticalCases: [
    {
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      riskBand: "Critical",
      triageScore: 88,
      overdueExposure: "286,000",
      reason: "Exposure threshold crossed with invoices beyond 60 days.",
      chips: ["60+ days overdue", "Policy threshold", "Large exposure"],
      recommendation: "Pause new credit orders pending manager decision.",
    },
    {
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      riskBand: "Critical",
      triageScore: 84,
      overdueExposure: "241,500",
      reason: "Strategic account with worsening payment trend.",
      chips: ["Strategic account", "Order decline", "Overdue trend"],
      recommendation: "Escalate for finance manager exception review.",
    },
    {
      caseId: "case_012",
      customerName: "Horizon Foodservice Trading Sdn Bhd",
      riskBand: "Watchlist",
      triageScore: 63,
      overdueExposure: "39,200",
      reason: "Borderline account ideal for scenario simulation.",
      chips: ["Rising overdue trend", "Partial payments", "Order decline"],
      recommendation: "Schedule monitored recovery call.",
    },
  ],
  activeRuns: [
    {
      runId: "run_20260326_live_001",
      customerName: "GreenWave Hospitality Group",
      status: "Running",
      node: "Policy Check Agent",
      elapsed: "11s",
    },
  ],
  pendingApprovals: [
    {
      approvalId: "app_201",
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      action: "Pause new credit orders",
      priority: "High",
      waiting: "68 min",
    },
    {
      approvalId: "app_202",
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      action: "Temporary monitored exception",
      priority: "High",
      waiting: "31 min",
    },
  ],
  demoWalkthrough: {
    recommendedCaseId: "case_012",
    recommendedCustomerName: "Horizon Foodservice Trading Sdn Bhd",
    steps: [
      "Open the customer case",
      "Run a live AI review",
      "Inspect the workflow trace",
      "Use the what-if simulator",
      "Compare the recommendation change",
    ],
  },
};

export const portfolioRows = [
  {
    caseId: "case_013",
    customerName: "HarborCare Corporate Services Pte Ltd",
    segment: "Office & Corporate Facilities",
    region: "Singapore",
    triageScore: 14,
    riskBand: "Low",
    overdueBalance: "0",
    oldestOverdueDays: "0",
    triggers: ["Stable payments"],
    recommendation: "No action needed",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_012",
    customerName: "Horizon Foodservice Trading Sdn Bhd",
    segment: "Hospitality & F&B",
    region: "Malaysia",
    triageScore: 63,
    riskBand: "Watchlist",
    overdueBalance: "39,200",
    oldestOverdueDays: "31",
    triggers: ["Rising overdue trend", "Partial payments"],
    recommendation: "Schedule monitored recovery call",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_002",
    customerName: "Meridian Retail Mart Sdn Bhd",
    segment: "Retail Chains",
    region: "Malaysia",
    triageScore: 72,
    riskBand: "High",
    overdueBalance: "118,000",
    oldestOverdueDays: "53",
    triggers: ["Broken promises", "Late-payment streak"],
    recommendation: "Escalate collections and reduce exposure",
    reviewMode: "Baseline",
  },
  {
    caseId: "case_011",
    customerName: "Titan Facility Management Pte Ltd",
    segment: "Facilities Management",
    region: "Singapore",
    triageScore: 88,
    riskBand: "Critical",
    overdueBalance: "162,000",
    oldestOverdueDays: "68",
    triggers: ["60+ days overdue", "Policy threshold"],
    recommendation: "Pause new credit orders pending approval",
    reviewMode: "Baseline",
  },
];

export const caseDetails: Record<string, any> = {
  case_002: {
    customerName: "Meridian Retail Mart Sdn Bhd",
    meta: "Retail Chains | Malaysia | 2.5 years | Net 30 | Credit Limit 120,000 | Owner: Iman R.",
    badges: ["Strategic: No", "Tier: Growth"],
    riskSnapshot: [
      { label: "Risk", value: "High" },
      { label: "Risk Score", value: "72" },
      { label: "Triage Score", value: "72" },
      { label: "Overdue", value: "118,000" },
      { label: "Oldest Due", value: "53d" },
      { label: "Approval", value: "Pending" },
    ],
    recommendation: {
      action: "Escalate collections and reduce exposure",
      why: "Repeated broken promises and chronic lateness indicate structural payment discipline issues.",
      tradeoff: "More forceful action protects cash exposure but increases relationship strain.",
      nextSteps: ["Escalate to collections manager", "Restrict incremental credit", "Review after next payment event"],
    },
    triage: {
      score: 72,
      riskBand: "High",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["Broken promises", "Late-payment streak"],
    },
    riskDrivers: ["Repeated broken promises", "53-day oldest overdue", "No dispute justification"],
    notes: [
      "Customer requested a few more days for the third time this month.",
      "Collections team recorded a missed promise-to-pay follow-up.",
      "Order volume remains stable but payment discipline is deteriorating.",
    ],
    policy: ["Repeat-default behavior rule active", "Manager review recommended before further credit expansion"],
  },
  case_007: {
    customerName: "GreenWave Hospitality Group",
    meta: "Hospitality & F&B | Singapore | 8 years | Net 45 | Credit Limit 300,000 | Owner: Alicia T.",
    badges: ["Strategic: Yes", "Tier: Enterprise"],
    riskSnapshot: [
      { label: "Risk", value: "Critical" },
      { label: "Risk Score", value: "84" },
      { label: "Triage Score", value: "84" },
      { label: "Overdue", value: "148,000" },
      { label: "Oldest Due", value: "58d" },
      { label: "Approval", value: "Required" },
    ],
    recommendation: {
      action: "Escalate for finance manager exception review",
      why: "The account is commercially important but now conflicts with policy thresholds and exception logic.",
      tradeoff: "Protects revenue relationship while preventing uncontrolled exposure growth.",
      nextSteps: ["Complete live policy review", "Route to approval queue", "Define monitored exception terms"],
    },
    triage: {
      score: 84,
      riskBand: "Critical",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["Strategic account", "Order decline", "Overdue trend"],
    },
    riskDrivers: ["Strategic exception pressure", "Worsening overdue trend", "Declining order profile"],
    notes: [
      "Commercial team requested softer handling due to contract renewal in progress.",
      "Finance noted overdue exposure now exceeds comfort range for normal monitored handling.",
      "Relationship remains important but operational confidence is weakening.",
    ],
    policy: ["High exposure threshold active", "Strategic exception requires manager approval"],
  },
  case_011: {
    customerName: "Titan Facility Management Pte Ltd",
    meta: "Facilities Management | Singapore | 5 years | Net 45 | Credit Limit 250,000 | Owner: Marcus L.",
    badges: ["Strategic: No", "Tier: Core"],
    riskSnapshot: [
      { label: "Risk", value: "Critical" },
      { label: "Risk Score", value: "88" },
      { label: "Triage Score", value: "88" },
      { label: "Overdue", value: "162,000" },
      { label: "Oldest Due", value: "68d" },
      { label: "Approval", value: "Required" },
    ],
    recommendation: {
      action: "Pause new credit orders pending approval",
      why: "Exposure thresholds are breached with multiple invoices beyond 60 days and no credible recovery update.",
      tradeoff: "This is the safest credit-control action, but it may disrupt ongoing business servicing.",
      nextSteps: ["Move to approval queue", "Pause new credit orders if approved", "Review after manager decision"],
    },
    triage: {
      score: 88,
      riskBand: "Critical",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["60+ days overdue", "Policy threshold", "Large exposure"],
    },
    riskDrivers: ["Large overdue exposure", "Multiple 60+ day invoices", "No active dispute mitigation"],
    notes: [
      "Collections calls have not produced a firm repayment timeline.",
      "Sales team is unsure whether the customer can clear the balance in the near term.",
      "New order requests continue despite unresolved aging pressure.",
    ],
    policy: ["Hard stop threshold crossed", "Manager approval mandatory before restrictive action"],
  },
  case_012: {
    customerName: "Horizon Foodservice Trading Sdn Bhd",
    meta: "Hospitality & F&B | Malaysia | 2 years | Net 30 | Credit Limit 110,000 | Owner: Farah N.",
    badges: ["Strategic: No", "Tier: Core"],
    riskSnapshot: [
      { label: "Risk", value: "Watchlist" },
      { label: "Risk Score", value: "64" },
      { label: "Triage Score", value: "63" },
      { label: "Overdue", value: "39,200" },
      { label: "Oldest Due", value: "31d" },
      { label: "Approval", value: "Not required" },
    ],
    recommendation: {
      action: "Schedule monitored recovery call",
      why: "The account is near a threshold where another missed payment could trigger stronger controls.",
      tradeoff: "Balances risk control with relationship preservation while the customer is still engaged.",
      nextSteps: [
        "Call customer within 48 hours",
        "Confirm repayment timeline",
        "Rerun review if no payment arrives",
      ],
    },
    triage: {
      score: 63,
      riskBand: "Watchlist",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["Rising overdue trend", "Partial payments", "Order decline"],
    },
    riskDrivers: [
      "Rising overdue trend",
      "Partial payment stress",
      "Slight order decline",
      "Near policy threshold",
    ],
    notes: [
      "Customer committed to partial payment this week pending receivables collection.",
      "Account manager notes relationship remains recoverable with structured follow-up.",
      "Recent order values softened over the last 2 months.",
    ],
    policy: ["Borderline exposure review trigger active", "No hard approval threshold crossed yet"],
  },
  case_013: {
    customerName: "HarborCare Corporate Services Pte Ltd",
    meta: "Office & Corporate Facilities | Singapore | 3 years | Net 30 | Credit Limit 90,000 | Owner: Darren K.",
    badges: ["Strategic: No", "Tier: Stable"],
    riskSnapshot: [
      { label: "Risk", value: "Low" },
      { label: "Risk Score", value: "14" },
      { label: "Triage Score", value: "14" },
      { label: "Overdue", value: "0" },
      { label: "Oldest Due", value: "0d" },
      { label: "Approval", value: "Not required" },
    ],
    recommendation: {
      action: "No action needed",
      why: "Payment behavior remains stable and no escalation signals are active.",
      tradeoff: "Avoids unnecessary review cost on a healthy account.",
      nextSteps: ["Keep in baseline monitoring", "Re-triage on next scheduled pass"],
    },
    triage: {
      score: 14,
      riskBand: "Low",
      source: "Auto-created from triage",
      latestBaselineReviewAt: "2026-03-26 09:00",
      triggers: ["Stable payments"],
    },
    riskDrivers: ["Healthy payment profile", "No dispute activity", "Stable order cadence"],
    notes: [
      "Recent invoices have been paid on or before due date.",
      "Account owner reports no relationship concerns.",
    ],
    policy: ["No active policy triggers"],
  },
};

export const traceData = {
  runId: "run_20260326_live_001",
  customerName: "GreenWave Hospitality Group",
  caseId: "case_007",
  status: "Running",
  duration: "12s",
  cost: "$0.27",
  activeNode: "Policy Check Agent",
  nodes: [
    {
      nodeId: "intake",
      label: "Case Intake Agent",
      status: "Completed",
      model: "gpt-5.4-nano",
      duration: "1.8s",
      summary: "Classified as a strategic high-exposure review case.",
    },
    {
      nodeId: "financial-risk",
      label: "Financial Risk Agent",
      status: "Completed",
      model: "gpt-5.4-mini",
      duration: "3.2s",
      summary: "Detected worsening aging profile and elevated exposure concentration.",
    },
    {
      nodeId: "relationship",
      label: "Relationship Agent",
      status: "Completed",
      model: "gpt-5.4-mini",
      duration: "2.6s",
      summary: "Flagged strategic importance and commercial sensitivity.",
    },
    {
      nodeId: "policy",
      label: "Policy Check Agent",
      status: "Running",
      model: "gpt-5.1",
      duration: "4.4s",
      summary: "Evaluating exception pathway against approval thresholds.",
    },
    {
      nodeId: "strategy",
      label: "Recovery Strategy Agent",
      status: "Queued",
      model: "gpt-5.4-mini",
      duration: "0s",
      summary: "Waiting for policy output before generating final action.",
    },
  ],
  toolCalls: [
    {
      toolCallId: "tc_201",
      nodeId: "financial-risk",
      mcpServer: "ar-analytics-mcp",
      toolName: "get_invoice_aging",
      latency: "218ms",
      input: "customer_id=cust_007",
      output: "Returned 14 invoice records with 58-day oldest overdue bucket.",
    },
    {
      toolCallId: "tc_202",
      nodeId: "relationship",
      mcpServer: "customer-profile-mcp",
      toolName: "get_customer_summary",
      latency: "144ms",
      input: "customer_id=cust_007",
      output: "Returned strategic account flag and account owner metadata.",
    },
    {
      toolCallId: "tc_203",
      nodeId: "relationship",
      mcpServer: "notes-policy-mcp",
      toolName: "get_customer_notes",
      latency: "172ms",
      input: "customer_id=cust_007",
      output: "Returned 7 relationship and collections notes.",
    },
  ],
  structuredOutputs: [
    {
      title: "Case Intake Plan",
      payload: {
        case_type: "strategic_exception_review",
        priority: "high",
        required_data_sources: "invoice_aging, payment_behavior, customer_notes, policy_rules",
      },
    },
    {
      title: "Financial Risk Assessment",
      payload: {
        risk_level: "Critical",
        overdue_severity: "severe",
        payment_behavior_pattern: "worsening_late_payment",
        confidence: "0.88",
      },
    },
    {
      title: "Relationship Assessment",
      payload: {
        relationship_health: "sensitive",
        strategic_importance: "high",
        recommended_tone: "controlled_exception_review",
      },
    },
  ],
  modelRouting: [
    ["Case Intake Agent", "gpt-5.4-nano", "cheap structured classification"],
    ["Financial Risk Agent", "gpt-5.4-mini", "default balanced reasoning model"],
    ["Relationship Agent", "gpt-5.4-mini", "default balanced reasoning model"],
    ["Policy Check Agent", "gpt-5.1", "stronger reasoning for approval-sensitive case"],
  ],
  events: [
    "Run started from customer case page",
    "Intake classified case as strategic exception review",
    "Financial risk analysis completed",
    "Relationship assessment completed",
    "Policy check still in progress",
  ],
};

export const simulationData = {
  customerName: "Horizon Foodservice Trading Sdn Bhd",
  caseId: "case_012",
  baseline: {
    riskLevel: "Watchlist",
    riskScore: 64,
    action: "Schedule monitored recovery call",
    approvalRequired: "No",
    topDrivers: ["Rising overdue trend", "Partial payment behavior", "Slight order decline"],
  },
  controls: [
    ["Days overdue delta", "+14"],
    ["Outstanding balance delta", "+8,500"],
    ["Partial payment amount", "0"],
    ["Broken promises delta", "+1"],
    ["Order trend", "Declining"],
    ["Dispute status", "Closed"],
    ["Strategic account", "No"],
    ["Credit limit", "110,000"],
    ["Payment terms", "Net 30"],
    ["Manager confidence", "42"],
  ],
  scenarioResult: {
    riskLevel: "High",
    riskScore: 78,
    action: "Escalate to finance manager and prepare credit limit reduction review",
    approvalRequired: "Yes",
    topDrivers: ["Threshold-crossing overdue exposure", "Repeated missed commitment risk", "Order decline"],
  },
  deltas: [
    "Overdue threshold crossed",
    "Approval now required",
    "Financial risk severity increased",
  ],
  policyImpact: ["High exposure escalation threshold", "Manager approval now mandatory"],
  savedScenarios: [
    ["Miss Another Payment", "High", "Approval required"],
    ["Receive Partial Payment", "Monitor", "No approval"],
  ],
};

export const approvalsData = {
  summary: [
    ["Pending", "2"],
    ["Approved Today", "5"],
    ["Rejected Today", "1"],
    ["Revision Requested", "1"],
  ],
  queue: [
    {
      approvalId: "app_201",
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      requestedAction: "Pause new credit orders",
      riskLevel: "Critical",
      priority: "High",
      policyReason: "Hard threshold crossed",
      waiting: "68 min",
      status: "Pending",
    },
    {
      approvalId: "app_202",
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      requestedAction: "Temporary monitored exception",
      riskLevel: "Critical",
      priority: "High",
      policyReason: "Strategic exception sign-off",
      waiting: "31 min",
      status: "Pending",
    },
  ],
  selected: {
    approvalId: "app_201",
    caseId: "case_011",
    customerName: "Titan Facility Management Pte Ltd",
    requestedAction: "Pause new credit orders",
    riskSummary: "Critical risk due to large overdue exposure and multiple invoices beyond 60 days.",
    policyReason: "Rule pol_03 and pol_09 require manager approval before restrictive credit action.",
    evidence: [
      ["Outstanding balance", "286,000"],
      ["Overdue balance", "162,000"],
      ["Oldest overdue", "68d"],
    ],
    topDrivers: ["Large overdue exposure", "Multiple 60+ day invoices", "No active dispute mitigation"],
    recommendation: "Pause new credit orders pending approval",
    tradeoff: "Protects cash exposure but may disrupt service continuity and strain the relationship.",
    auditHistory: [
      "Approval requested after live review crossed a hard policy threshold.",
      "Portfolio triage created the case due to severe overdue exposure.",
    ],
  },
};

export const casesData = {
  summary: [
    ["Total Cases", "14"],
    ["New", "1"],
    ["In Review", "4"],
    ["Awaiting Approval", "2"],
    ["Resolved", "2"],
    ["Rejected", "1"],
  ],
  rows: [
    {
      caseId: "case_001",
      customerName: "Apex Facilities & Office Care Pte Ltd",
      region: "Singapore",
      segment: "Office & Corporate Facilities",
      status: "In Review",
      priority: "Medium",
      triggerReason: "Strategic customer under temporary cashflow stress",
      latestRecommendation: "Schedule relationship-led recovery call",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 09:20",
    },
    {
      caseId: "case_002",
      customerName: "Meridian Retail Mart Sdn Bhd",
      region: "Malaysia",
      segment: "Retail Chains",
      status: "In Review",
      priority: "High",
      triggerReason: "Repeated broken promises and late-payment streak",
      latestRecommendation: "Escalate collections and reduce exposure",
      approvalStatus: "Pending",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 09:38",
    },
    {
      caseId: "case_003",
      customerName: "Urban Harvest Kitchens Pte Ltd",
      region: "Singapore",
      segment: "Hospitality & F&B",
      status: "In Review",
      priority: "High",
      triggerReason: "Large overdue balance with active partial repayments",
      latestRecommendation: "Propose formal installment plan",
      approvalStatus: "Pending",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 08:54",
    },
    {
      caseId: "case_004",
      customerName: "NovaPack Print & Display Sdn Bhd",
      region: "Malaysia",
      segment: "Retail Chains",
      status: "Resolved",
      priority: "Medium",
      triggerReason: "Invoice dispute driving delayed payment",
      latestRecommendation: "Route to dispute resolution first",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-25 17:10",
    },
    {
      caseId: "case_005",
      customerName: "Silverline Engineering Supplies Pte Ltd",
      region: "Singapore",
      segment: "Light Industrial & Warehouse",
      status: "New",
      priority: "High",
      triggerReason: "Shrinking orders plus worsening payment behavior",
      latestRecommendation: "Escalate to account review",
      approvalStatus: "None",
      latestRunStatus: "Not started",
      updatedAt: "2026-03-26 10:14",
    },
    {
      caseId: "case_006",
      customerName: "BluePeak Trading Sdn Bhd",
      region: "Malaysia",
      segment: "Light Industrial & Warehouse",
      status: "Approved",
      priority: "High",
      triggerReason: "New customer deteriorating quickly",
      latestRecommendation: "Tighten terms and pause growth on credit",
      approvalStatus: "Approved",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 07:48",
    },
    {
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      region: "Singapore",
      segment: "Hospitality & F&B",
      status: "Awaiting Approval",
      priority: "High",
      triggerReason: "Strategic exception review required",
      latestRecommendation: "Escalate for finance manager exception review",
      approvalStatus: "Pending",
      latestRunStatus: "Running",
      updatedAt: "2026-03-26 10:42",
    },
    {
      caseId: "case_008",
      customerName: "Delta Clinical Services Sdn Bhd",
      region: "Malaysia",
      segment: "Clinics & Healthcare Services",
      status: "Approved",
      priority: "Medium",
      triggerReason: "Chronic mild lateness but high long-term value",
      latestRecommendation: "Maintain account with controlled monitoring",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-24 12:18",
    },
    {
      caseId: "case_009",
      customerName: "Orion Workspace Solutions Pte Ltd",
      region: "Singapore",
      segment: "Office & Corporate Facilities",
      status: "Resolved",
      priority: "Low",
      triggerReason: "Prior stress pattern improving",
      latestRecommendation: "De-escalate to monitoring",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-23 16:42",
    },
    {
      caseId: "case_010",
      customerName: "Summit Lifestyle Retail Sdn Bhd",
      region: "Malaysia",
      segment: "Retail Chains",
      status: "Approved",
      priority: "Medium",
      triggerReason: "Negative qualitative signals despite moderate numeric risk",
      latestRecommendation: "Proactive review call and tighter follow-up cadence",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 09:06",
    },
    {
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      region: "Singapore",
      segment: "Facilities Management",
      status: "Awaiting Approval",
      priority: "High",
      triggerReason: "Large exposure crossing hard policy threshold",
      latestRecommendation: "Pause new credit orders pending approval",
      approvalStatus: "Pending",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 09:45",
    },
    {
      caseId: "case_012",
      customerName: "Horizon Foodservice Trading Sdn Bhd",
      region: "Malaysia",
      segment: "Hospitality & F&B",
      status: "In Review",
      priority: "Medium",
      triggerReason: "Borderline case for simulation and monitored recovery",
      latestRecommendation: "Schedule monitored recovery call",
      approvalStatus: "None",
      latestRunStatus: "Running",
      updatedAt: "2026-03-26 11:02",
    },
    {
      caseId: "case_013",
      customerName: "HarborCare Corporate Services Pte Ltd",
      region: "Singapore",
      segment: "Office & Corporate Facilities",
      status: "Approved",
      priority: "Low",
      triggerReason: "Healthy account baseline review",
      latestRecommendation: "No action needed",
      approvalStatus: "None",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-26 09:00",
    },
    {
      caseId: "case_014",
      customerName: "MetroMed Support Supplies Sdn Bhd",
      region: "Malaysia",
      segment: "Clinics & Healthcare Services",
      status: "Rejected",
      priority: "Low",
      triggerReason: "Stable account review raised no actionable concerns",
      latestRecommendation: "No action needed",
      approvalStatus: "Rejected",
      latestRunStatus: "Completed",
      updatedAt: "2026-03-24 11:03",
    },
  ],
  activityFeed: [
    {
      eventId: "evt_1001",
      caseId: "case_012",
      customerName: "Horizon Foodservice Trading Sdn Bhd",
      timestamp: "2026-03-26 11:02",
      summary: "Simulation-ready review completed with monitored recovery recommendation.",
    },
    {
      eventId: "evt_1002",
      caseId: "case_011",
      customerName: "Titan Facility Management Pte Ltd",
      timestamp: "2026-03-26 09:45",
      summary: "Approval requested for restrictive credit action.",
    },
    {
      eventId: "evt_1003",
      caseId: "case_007",
      customerName: "GreenWave Hospitality Group",
      timestamp: "2026-03-26 10:42",
      summary: "Live strategic exception review started from case page.",
    },
    {
      eventId: "evt_1004",
      caseId: "case_005",
      customerName: "Silverline Engineering Supplies Pte Ltd",
      timestamp: "2026-03-26 10:14",
      summary: "Case created from new portfolio triage signal.",
    },
  ],
};
